### ISSUE TITLE
Rename GitHub Action to "fontist/setup"

### ISSUE THREAD

**Issue by ronaldtse** [fontist/setup-fontist#3]
Right now the action is called "fontist/setup-fontist", but it would sound much better to be `fontist/setup`.

**Comment by jcbhmr** [comment]
I recommend conforming with existing ecosystem convention and naming this action "fontist/setup-fontist". It makes it seem more "normal" and less "huh they're weird". Sorta like it'd be weird to see Ruby code with camelCase variable name style lol.

Here's some examples of popular organizations using "org/setup-thing" as the go-to de-facto naming convention for "$THING installer" actions:
- https://github.com/ruby/setup-ruby
- https://github.com/ocaml/setup-ocaml
- https://github.com/oras-project/setup-oras
- https://github.com/google-github-actions/setup-gcloud
- https://github.com/shivammathur/setup-php
- https://github.com/hashicorp/setup-terraform
- https://github.com/docker/setup-buildx-action
- https://github.com/microsoft/setup-msbuild
- https://github.com/conda-incubator/setup-miniconda
- https://github.com/hashicorp/setup-packer
- the list really does go on https://github.com/search?q=setup-+in%3Aname&type=repositories (there's no way to filter to just actions 😢)

From a more practical point of view, this also lets you have multiple "setup-$THING" actions such as setup-excavate https://github.com/fontist/excavate or $some_future_cli_tool without the root "fontist/setup" thing getting "well does it setup _everthing_? or do i have to pick? is it a monorepo?" confusing.

---

This is also a good time to clarify: Why "fontist-version" for input instead of just "version"? Because it's the convention. Especially among @actions. https://github.com/actions/setup-node/blob/main/action.yml#L8 It _could_ go either way but disambiguating "fontist-version" leaves a spot for a "ruby-version" input if needed 😉

**Comment by ronaldtse** [comment]
@jcbhmr there are also other GitHub Action patterns such as:

`{org}/{action-name}`
* https://github.com/marketplace/actions/cache
* https://github.com/marketplace/actions/checkout

`{org}/action[s]-{action-name}`
* https://github.com/peaceiris/actions-gh-pages
* https://github.com/softprops/action-gh-release

`{org}/actions/{action-name}`
* https://github.com/r-lib/actions

I wonder if the last would be technically the cleanest since all the actions can be packed in the same repo, separating GitHub Actions from code proper.

For now though I agree we can stick with a convention similar to `ruby/setup-ruby`.
